changes to maps on all pages
ericnost/streamlit_test pull request #42
Opened 2023-07-11 21:31 UTC by ericnost

Fixes #26
Fixes #35
Fixes #22
Fixes #12

2023-07-11 21:34 UTC, ericnost commented
I built this branch on `main` rather than #38, which was maybe a mistake, but I'm happy to fix any conflicts if it comes to it.

These changes address several of the map-related issues I think. Reduces load time and glitchiness, creates a default box defining an area for users to explore, changes some symbolization, adds a legend, changes map sizes to be as responsive as possible.

2023-07-13 03:37 UTC, Frijol commented on pages/1_🌍_Statewide_Overview.py
> -    with st.spinner(text="Loading interactive map..."):
Would be good to keep the spinner!

2023-07-13 03:38 UTC, Frijol requested changes
This is a big improvement! I think the spinner on the Statewide Overview page accidentally got deleted, but once that's back I think it's good to go.

2023-07-13 04:11 UTC, Frijol approved these changes

2023-07-13 04:11 UTC, merged